name: fast_market
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  go_router: ^13.0.0
  flutter_riverpod: ^2.4.9 #상태관리

  google_sign_in: ^6.1.4  #구글 로그인

  image_picker: ^1.0.5  #이미지 가져오기
  intl: ^0.19.0         #데이터 포맷
  dots_indicator: ^3.0.0  #배너 도트

  camera: ^0.10.5+7

  freezed_annotation: ^2.4.1  #데이터 클레스(모델) 만들기
  json_annotation: ^4.8.1

  flutter_image_compress: ^2.1.0 #이미지 압축

  #firebase
  firebase_core: ^2.24.2
  firebase_auth: ^4.15.3
  cloud_firestore: ^4.13.6
  firebase_storage: ^11.5.6

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.1

  build_runner: ^2.4.7 #freezed 사용 목적
  freezed: ^2.4.6
  json_serializable: ^6.7.1

flutter:

  uses-material-design: true

  assets:
    - assets/
